#-------------------------------------------------------------------------------#
# If disable PCL point clouds as input
DisablePCL: false
# Use self-defined point type
CustomizePointType: true

#-------------------------------------------------------------------------------#
# Number of the times of running
RunNum: 1

#-------------------------------------------------------------------------------#
# Choose the source of points
#-------------------------------------------------------------------------------#
InputFromFile: false
#---------------------#
# if InputFromFile
InputPointCloudFile: "/home/wxxs6p/repo/gDel2D-edition/app/test1/slices/slice_138.pcd"
InputConstraintFile: ""
#---------------------#
# if NOT InputFromFile
PointNum: 1000
# Choose among {"Uniform", "Gaussian", "Disk", "ThinCircle", "Circle", "Grid", "Ellipse", "TwoLines"}
DistributionType: "Uniform"
# Initial seed
Seed: 76213898
# Save randomly generated points
SaveToFile: false
SavePath: "/home/wxxs6p/Documents/private/gpu-delaunay-generator-2.5D/example_points.txt"
#-------------------------------------------------------------------------------#
# Insert all before flipping
InsertAll: false
# Sort input points
NoSortPoint: false
# Reorder the triangle before flipping
NoReorder: false
# Check Euler, orientation, etc.
DoCheck: false

# Output check/triangulation result
OutputTriangles: true
# Choose among {".geojson", ".obj"}
OutputTrianglePath: "/home/wxxs6p/Documents/data/example_tri.obj"
